services:
  app:
    image: cyberctf/username-enumeration-via-different-responses:latest
    container_name: employee-portal-prod
    ports:
      - "3206:3206"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    volumes:
      - employee_data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3206/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  employee_data: